### ISSUE TITLE
tsk silently fails if a .env file doesn't exist

### ISSUE THREAD

**Issue by notnmeyer** [notnmeyer/tsk#110]
```toml file=tasks.toml
dotenv = ".doesnt-exist"

[tasks.example]
cmds = ["echo 'blah'"]
```

```
✦ ➜ tsk example ; echo $status
0
```

should either error and exit 1, or display a warning about the env file not being present
